services:
  - type: web
    name: ai-blog-generator
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd ai_blogger && gunicorn ai_blogger.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0